testing arm build with opencv.

diff --git a/dockerfiles/harmoni/kinetic/base/dockerfile b/dockerfiles/harmoni/kinetic/base/dockerfile
--- a/dockerfiles/harmoni/kinetic/base/dockerfile
+++ b/dockerfiles/harmoni/kinetic/base/dockerfile
@@ -1,3 +1,118 @@
+# ==================================================================
+# OpenCV build
+# ------------------------------------------------------------------
+ARG PYTHON_VERSION_SHORT=3.6
+ARG OPENCV_VERSION=4.4.0
+ARG CPU_CORES=4
+
+FROM python:3.6-stretch AS cv
+
+ARG DEBIAN_FRONTEND=noninteractive
+
+# Installing build tools and dependencies.
+# More about dependencies there: https://docs.opencv.org/4.0.0/d2/de6/tutorial_py_setup_in_ubuntu.html
+RUN set -e; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+        apt-utils \
+        build-essential; \
+    apt-get install -y --no-install-recommends \
+        # Downloading utils
+        unzip \
+        wget \
+        # Build utils
+        cmake \
+        gcc \
+        # Required dependencies
+        python-numpy \
+        libavcodec-dev \
+        libavformat-dev \
+        libswscale-dev \
+        libgstreamer-plugins-base1.0-dev \
+        # Optional dependencies
+        libtbb2 \
+        libtbb-dev \
+        libjpeg-dev \
+        libpng-dev \
+        libopenexr-dev \
+        libtiff-dev \
+        libwebp-dev \
+        # Video device drivers
+        libv4l-dev \
+        libdc1394-22-dev; \
+    # Clear apt cache
+    rm -rf /var/lib/apt/lists/*
+
+RUN pip install numpy
+
+ARG OPENCV_VERSION
+ENV OPENCV_VERSION=$OPENCV_VERSION
+
+# Download latest source and contrib
+RUN set -e; \
+    cd /tmp; \
+    wget -c -nv -O opencv.zip https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip; \
+    unzip opencv.zip; \
+    wget -c -nv -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/$OPENCV_VERSION.zip; \
+    unzip opencv_contrib.zip
+
+ARG PYTHON_VERSION_SHORT
+ENV PYTHON_VERSION=$PYTHON_VERSION_SHORT
+
+ARG CPU_CORES
+
+# Build opencv
+RUN set -e; \
+    cd /tmp/opencv-$OPENCV_VERSION; \
+    mkdir build; \
+    cd build; \
+    mkdir /opt/opencv; \
+    cmake -D CMAKE_BUILD_TYPE=RELEASE \
+        -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib-$OPENCV_VERSION/modules \
+        -D CMAKE_INSTALL_PREFIX=/opt/opencv \
+        # Build without GUI support
+        -D WITH_QT=OFF \
+        -D WITH_GTK=OFF \
+        # Build without GPU support
+        -D WITH_OPENCL=OFF \
+        -D WITH_CUDA=OFF \
+        -D BUILD_opencv_gpu=OFF \
+        -D BUILD_opencv_gpuarithm=OFF \
+        -D BUILD_opencv_gpubgsegm=OFF \
+        -D BUILD_opencv_gpucodec=OFF \
+        -D BUILD_opencv_gpufeatures2d=OFF \
+        -D BUILD_opencv_gpufilters=OFF \
+        -D BUILD_opencv_gpuimgproc=OFF \
+        -D BUILD_opencv_gpulegacy=OFF \
+        -D BUILD_opencv_gpuoptflow=OFF \
+        -D BUILD_opencv_gpustereo=OFF \
+        -D BUILD_opencv_gpuwarping=OFF \
+        # Build with python
+        -D BUILD_opencv_python3=ON \
+        -D BUILD_opencv_python2=OFF \
+        -D PYTHON_DEFAULT_EXECUTABLE=$(which python${PYTHON_VERSION}) \
+        # Ignore all unnecessary stages
+        -D BUILD_opencv_apps=OFF \
+        -D BUILD_EXAMPLES=OFF \
+        -D INSTALL_C_EXAMPLES=OFF \
+        -D INSTALL_PYTHON_EXAMPLES=OFF \
+        -D BUILD_DOCS=OFF \
+        -D BUILD_PERF_TESTS=OFF \
+        -D BUILD_TESTS=OFF \
+        ..; \
+    make -j$CPU_CORES; \
+    make install; \
+    ldconfig; \
+    # Clean up
+    make clean; \
+    cd /tmp; \
+    rm -rf /tmp/* \
+    #make sure python will see the package. NOTE: this step needs to run on the destination container
+CMD ["/bin/bash"]
+
+# ==================================================================
+# Main Container build
+# ------------------------------------------------------------------
 FROM ubuntu:xenial
 
 RUN ROS_DISTRO="kinetic"
@@ -32,20 +147,6 @@ RUN \
     # NETWORK TOOLS
     iputils-ping \
     net-tools \
-    # ==================================================================
-    # Compile and install latest cmake (note there will be two versions installed)
-    # ------------------------------------------------------------------
-    && version=3.18 \
-    && build=4  \
-    && wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz \
-    && tar -xzf cmake-$version.$build.tar.gz \
-    && cd cmake-$version.$build/ \
-    && ./bootstrap \
-    && make -j$(nproc) \
-    && make install \
-    && cd ../ \
-    && rm -r cmake-$version.$build.tar.gz cmake-$version.$build \
-    && cmake --version \
     # ==================================================================
     # Setup Python3.6 with pip
     # ------------------------------------------------------------------
@@ -172,7 +273,6 @@ RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
     empy \
     PyAudio \
     imutils \
-    opencv-python \
     --force-reinstall defusedxml \
     # ==================================================================
     # Install the Ros packages needed for Harmoni
@@ -184,3 +284,10 @@ RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
     ros-$ROS_DISTRO-audio-common \
     && \
     rm -rf /var/lib/apt/lists/* /tmp/*
+
+    # ==================================================================
+    # Install Built OpenCV
+    # ------------------------------------------------------------------
+    COPY --from=cv /opt/opencv /opt/opencv
+    #make sure python will see the package.
+    RUN ln -s /opt/opencv/lib/python3.6/site-packages/cv2 /usr/local/lib/python3.6/site-packages/cv2 
